"""Email the expense report (PDF + Excel) to the submitter's manager and finance.

Configure with environment variables (put them in .env):
    SMTP_HOST=smtp.gmail.com  SMTP_PORT=587  SMTP_USER=you@gmail.com  SMTP_PASS=<app password>
    SMTP_FROM=you@gmail.com   (optional, defaults to SMTP_USER)
For Gmail create an App Password (Google Account -> Security -> 2-Step Verification -> App passwords).
"""
from __future__ import annotations

import os
import smtplib
from email.message import EmailMessage
from typing import List

from .models import ProcessResult


def configured() -> bool:
    return bool(os.environ.get("SMTP_HOST") and os.environ.get("SMTP_USER") and os.environ.get("SMTP_PASS"))


def _money(x, cur):
    return "—" if x is None else f"{cur} {x:,.2f}"


def build_body(res: ProcessResult, org_name: str) -> tuple[str, str]:
    p = res.profile
    cur = p.currency or "INR"
    verified = res.state.value == "VERIFIED"
    subject = f"[{org_name or 'Expense'}] {p.vendor_name or 'Receipt'} · {_money(p.total, cur)} · {'VERIFIED' if verified else 'NEEDS REVIEW'}"
    lines = [
        f"Expense report generated by the receipt agent{' for ' + org_name if org_name else ''}.",
        "",
        f"Submitted by : {res.submitted_by or 'unknown'}" + (f" ({res.department})" if res.department else ""),
        f"Vendor       : {p.vendor_name or '—'}",
        f"Date         : {p.date or '—'}",
        f"Total        : {_money(p.total, cur)}",
        f"Category     : {res.category}",
        f"Status       : {res.state.value}" + ("" if verified else "  <- arithmetic could not be reconciled; please review"),
        f"Policy       : {res.policy.status.replace('_', ' ')}" + (f" (rules {', '.join(res.policy.rules_triggered)})" if res.policy.rules_triggered else "") + f" — {res.policy.reason}",
    ]
    if res.duplicate.is_duplicate:
        lines.append(f"WARNING      : possible duplicate submission. {res.duplicate.detail}")
    lines += ["", "Line items:"]
    for li in p.line_items:
        lines.append(f"  - {li.description}: {_money(li.amount, cur)}")
    if res.iterations:
        lines += ["", f"The agent ran {res.iterations} self-correction pass(es):"]
        for t in res.trace:
            if t.state.value == "FLAGGED_FOR_REEXAMINATION" and t.revision_notes:
                lines.append(f"  - {t.revision_notes}")
    lines += ["", "The PDF report and Excel workbook are attached.", f"Receipt ID: {res.id}"]
    return subject, "\n".join(lines)


def send_report(res: ProcessResult, to: List[str], pdf: bytes, xlsx: bytes, org_name: str = "") -> str:
    if not configured():
        raise RuntimeError("Email is not configured. Set SMTP_HOST, SMTP_USER, SMTP_PASS (and optionally SMTP_PORT, SMTP_FROM) in .env.")
    to = [t.strip() for t in to if t and t.strip()]
    if not to:
        raise RuntimeError("No recipient: add a manager or finance email in the Organisation tab.")
    subject, body = build_body(res, org_name)
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = os.environ.get("SMTP_FROM") or os.environ["SMTP_USER"]
    msg["To"] = ", ".join(to)
    msg.set_content(body)
    msg.add_attachment(pdf, maintype="application", subtype="pdf", filename=f"expense-report-{res.id}.pdf")
    msg.add_attachment(xlsx, maintype="application", subtype="vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                       filename=f"expense-{res.id}.xlsx")
    host, port = os.environ["SMTP_HOST"], int(os.environ.get("SMTP_PORT", "587"))
    if port == 465:
        with smtplib.SMTP_SSL(host, port, timeout=30) as s:
            s.login(os.environ["SMTP_USER"], os.environ["SMTP_PASS"])
            s.send_message(msg)
    else:
        with smtplib.SMTP(host, port, timeout=30) as s:
            s.starttls()
            s.login(os.environ["SMTP_USER"], os.environ["SMTP_PASS"])
            s.send_message(msg)
    return ", ".join(to)
