"""Email the expense report (PDF + Excel) to the submitter's manager and finance.

Configure with environment variables (put them in .env):
    SMTP_HOST=smtp.gmail.com  SMTP_PORT=587  SMTP_USER=you@gmail.com  SMTP_PASS=<app password>
    SMTP_FROM=you@gmail.com   (optional, defaults to SMTP_USER)
For Gmail create an App Password (Google Account -> Security -> 2-Step Verification -> App passwords).
"""
from __future__ import annotations

import os
import smtplib
from email.message import EmailMessage
from typing import List

from .models import ProcessResult


def smtp_configured() -> bool:
    return bool(os.environ.get("SMTP_HOST") and os.environ.get("SMTP_USER") and os.environ.get("SMTP_PASS"))


def brevo_configured() -> bool:
    """Brevo (ex-Sendinblue) HTTPS API - works where hosts block outbound SMTP ports (e.g. Railway trial).
    BREVO_API_KEY=xkeysib-...  and  SMTP_FROM=<a sender address verified in Brevo>"""
    return bool(os.environ.get("BREVO_API_KEY") and os.environ.get("SMTP_FROM"))


def configured() -> bool:
    return brevo_configured() or smtp_configured()


def _brevo_send(to: List[str], subject: str, text: str, attachments: list[tuple[str, bytes]] = ()) -> None:
    import base64

    import requests

    payload = {
        "sender": {"email": os.environ["SMTP_FROM"], "name": os.environ.get("MAIL_FROM_NAME", "Receipt Agent")},
        "to": [{"email": t} for t in to],
        "subject": subject,
        "textContent": text,
    }
    if attachments:
        payload["attachment"] = [{"name": n, "content": base64.b64encode(b).decode()} for n, b in attachments]
    r = requests.post("https://api.brevo.com/v3/smtp/email", json=payload, timeout=30,
                      headers={"api-key": os.environ["BREVO_API_KEY"], "accept": "application/json"})
    if r.status_code >= 300:
        raise RuntimeError(f"Brevo rejected the email ({r.status_code}): {r.text[:200]}")


def _money(x, cur):
    return "—" if x is None else f"{cur} {x:,.2f}"


def build_body(res: ProcessResult, org_name: str) -> tuple[str, str]:
    p = res.profile
    cur = p.currency or "INR"
    verified = res.state.value == "VERIFIED"
    subject = f"[{org_name or 'Expense'}] {p.vendor_name or 'Receipt'} · {_money(p.total, cur)} · {'VERIFIED' if verified else 'NEEDS REVIEW'}"
    lines = [
        f"Expense report generated by the receipt agent{' for ' + org_name if org_name else ''}.",
        "",
        f"Submitted by : {res.submitted_by or 'unknown'}" + (f" ({res.department})" if res.department else ""),
        f"Vendor       : {p.vendor_name or '—'}",
        f"Date         : {p.date or '—'}",
        f"Total        : {_money(p.total, cur)}",
        f"Category     : {res.category}",
        f"Status       : {res.state.value}" + ("" if verified else "  <- arithmetic could not be reconciled; please review"),
        f"Policy       : {res.policy.status.replace('_', ' ')}" + (f" (rules {', '.join(res.policy.rules_triggered)})" if res.policy.rules_triggered else "") + f" — {res.policy.reason}",
    ]
    if res.duplicate.is_duplicate:
        lines.append(f"WARNING      : possible duplicate submission. {res.duplicate.detail}")
    lines += ["", "Line items:"]
    for li in p.line_items:
        lines.append(f"  - {li.description}: {_money(li.amount, cur)}")
    if res.iterations:
        lines += ["", f"The agent ran {res.iterations} self-correction pass(es):"]
        for t in res.trace:
            if t.state.value == "FLAGGED_FOR_REEXAMINATION" and t.revision_notes:
                lines.append(f"  - {t.revision_notes}")
    lines += ["", "The PDF report and Excel workbook are attached.", f"Receipt ID: {res.id}"]
    return subject, "\n".join(lines)


def _send(msg: EmailMessage) -> None:
    host, port = os.environ["SMTP_HOST"], int(os.environ.get("SMTP_PORT", "587"))
    if port == 465:
        with smtplib.SMTP_SSL(host, port, timeout=30) as s:
            s.login(os.environ["SMTP_USER"], os.environ["SMTP_PASS"])
            s.send_message(msg)
    else:
        with smtplib.SMTP(host, port, timeout=30) as s:
            s.starttls()
            s.login(os.environ["SMTP_USER"], os.environ["SMTP_PASS"])
            s.send_message(msg)


def send_plain(to: str, subject: str, body: str) -> None:
    if not configured():
        raise RuntimeError("Email is not configured.")
    if brevo_configured():
        return _brevo_send([to], subject, body)
    msg = EmailMessage()
    msg["Subject"], msg["To"] = subject, to
    msg["From"] = os.environ.get("SMTP_FROM") or os.environ["SMTP_USER"]
    msg.set_content(body)
    _send(msg)


def send_report(res: ProcessResult, to: List[str], pdf: bytes, xlsx: bytes, org_name: str = "") -> str:
    if not configured():
        raise RuntimeError("Email is not configured. Set BREVO_API_KEY + SMTP_FROM, or SMTP_HOST/SMTP_USER/SMTP_PASS, in .env.")
    to = [t.strip() for t in to if t and t.strip()]
    if not to:
        raise RuntimeError("No recipient: add a manager or finance email in the Organisation tab.")
    subject, body = build_body(res, org_name)
    if brevo_configured():
        _brevo_send(to, subject, body, [(f"expense-report-{res.id}.pdf", pdf), (f"expense-{res.id}.xlsx", xlsx)])
        return ", ".join(to)
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = os.environ.get("SMTP_FROM") or os.environ["SMTP_USER"]
    msg["To"] = ", ".join(to)
    msg.set_content(body)
    msg.add_attachment(pdf, maintype="application", subtype="pdf", filename=f"expense-report-{res.id}.pdf")
    msg.add_attachment(xlsx, maintype="application", subtype="vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                       filename=f"expense-{res.id}.xlsx")
    _send(msg)
    return ", ".join(to)
